<?php
    session_start();
    if (!isset($_SESSION['username'])) {
        header('Location: signin.php');
    } elseif ($_SERVER['REQUEST_METHOD'] === 'GET') {
    $username = $_SESSION['username'];
    $response['username'] = $username;
    $postdata = http_build_query($response);
    $opts = array('http' =>
        array(
            'method' => 'POST',
            'header' => 'Content-type: application/x-www-form-urlencoded',
            'content' => $postdata
        )
        );
    $context = stream_context_create($opts);
    $result = file_get_contents('http://localhost:5000/api/create2fa', false, $context);
    $response = json_decode($result, true);
        if ($response['status'] == '0') {
            $qr = $response['message'];
            ?>
            <!DOCTYPE html>
            <html lang="en">
            <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Set up Two-Factor Authentication - Sky Airlines</title>
            <link rel="icon" href="../images/navbar-logo.png">
            <link rel="stylesheet" href="../stylesheets/global.css">
            <link rel="stylesheet" href="../stylesheets/signin.css">
        </head>
        <body>
        <?php include '../navbar_2fa.php';?>
            <div id="signinarea">
            <h2>Set up Two-Factor Authentication (2FA)</h2>
            <h3>Please use your mobile authenticator app to scan the QR Code.</h3>
            <img src="data:image/png;base64,<?= $qr ?>" alt="QR Code">
            <form action="#" method="POST">
                <label for="password">One-time password generated by the authenticator app</label>
                <input type="password" id="signinarea-password" name="otp" required minlength="6" maxlength="6">
                <button type="submit">Confirm</button>
            </form>
        </div>
        <?php include '../footer.php';?>
        </body>
        </html>
            <?php
        } else {
            echo '<script>alert("An error occurred. Please try again.")</script><html><head><meta http-equiv="refresh" content="0;url=../myac.php"></head></html>';
        }
    } elseif ($_SERVER['REQUEST_METHOD'] === 'POST') {
        $username = $_SESSION['username'];
        $response = $_POST;
        $response['username'] = $username;
        $response['otp'] = $_POST['otp'];
        $postdata = http_build_query($response);
        $opts = array('http' =>
            array(
                'method' => 'POST',
                'header' => 'Content-type: application/x-www-form-urlencoded',
                'content' => $postdata
            )
        );
        $context = stream_context_create($opts);
        $result = file_get_contents('http://localhost:5000/api/setup2fa', false, $context);
        $response = json_decode($result, true);
        if ($response['status'] == '0') {
            echo '<script>alert("Two-Factor Authentication has set up successfully.")</script><html><head><meta http-equiv="refresh" content="0;url=../myac.php"></head></html>';
        } elseif ($response['status'] == '1') {
            echo '<script>alert("One time password is incorrect, please remove your account from your authenticator app and try again.")</script><html><head><meta http-equiv="refresh" content="0;url=../myac.php"></head></html>';
        } else {
            echo '<script>alert("An error occurred. Please try again.")</script><html><head><meta http-equiv="refresh" content="0;url=../myac.php"></head></html>';
        }
    } else {
        echo '<script>alert("An error occurred. Please try again.")</script><html><head><meta http-equiv="refresh" content="0;url=../myac.php"></head></html>';
    }
?>